CREATE SEQUENCE IS_TBL_USUARIO_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE IS_TBL_USUARIO (
    ID INTEGER DEFAULT IS_TBL_USUARIO_SEQ.NEXTVAL NOT NULL,
    NUMERO_CONTATO VARCHAR2(20) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
    EQUIPE VARCHAR(100) NOT NULL,
    FUNCAO VARCHAR(100) NOT NULL

);