CREATE SEQUENCE SEQ_PORTAS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE IS_TBL_PORTAS (
    PORTA_ID INTEGER DEFAULT SEQ_PORTAS.NEXTVAL NOT NULL,
    NR_PORTA INTEGER NOT NULL,
    CLIENTE VARCHAR2(50) NOT NULL,
    STATUS VARCHAR2(30) NOT NULL,
    PLOTADO NUMBER(1) DEFAULT 0 CHECK (plotado IN (0, 1)),
    OBSERVACAO VARCHAR2(100)
);