-- Criar sequence da conferência
CREATE SEQUENCE SEQ_CONFERENCIA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Criar tabela de conferência
CREATE TABLE IS_TBL_CONFERENCIA (
    ID_CONFERENCIA NUMBER(38,0) DEFAULT SEQ_CONFERENCIA.NEXTVAL NOT NULL,
    CAIXA VARCHAR2(100) NOT NULL,
    CIDADE VARCHAR2(100) NOT NULL,
    DATA_CONFERENCIA DATE NOT NULL,
    OBSERVACAO VARCHAR2(255),

    TECINTERNO_ID NUMBER(38,0) NOT NULL,
    TECEXTERNO_ID NUMBER(38,0) NOT NULL,

    CONSTRAINT PK_CONFERENCIA PRIMARY KEY (ID_CONFERENCIA),

    CONSTRAINT FK_CONFERENCIA_TECINTERNO FOREIGN KEY (TECINTERNO_ID)
        REFERENCES IS_TBL_USUARIO(ID),

    CONSTRAINT FK_CONFERENCIA_TECEXTERNO FOREIGN KEY (TECEXTERNO_ID)
        REFERENCES IS_TBL_USUARIO(ID)
);

-- Alterar tabela PORTAS para criar FK de conferência
ALTER TABLE IS_TBL_PORTAS
    ADD CONSTRAINT FK_PORTAS_CONFERENCIA
    FOREIGN KEY (CONFERENCIA_ID)
    REFERENCES IS_TBL_CONFERENCIA(ID_CONFERENCIA);
